### ISSUE TITLE
uberon clean up and synonyms

### ISSUE THREAD

**Issue by megbalk** [futres/fovt#41]
fused metapodials follow two different forms
make synonym for secondary/permanent and primary/deciduous for teeth
intertragic incisure is also the notch
upper canine 1 should be upper canine tooth 1
upper molar 1 should be upper molar tooth 1

Add abbreviations for teeth

**Comment by megbalk** [comment]
How often does one need to make parent terms?
for example, in UBERON "lower deciduous premolar 5" is defined as 'deciduous premolar 5' and ('part of' some 'upper jaw region'). It'd make more sense as 'premolar 5' and ('part of' some 'upper jaw region') and ('part of' some 'deciduous tooth or deciduous premolar tooth'). 

Or premolar tooth has subclasses: lower premolar tooth, lower deciduous premolar tooth...etc.

@ramonawalls any thoughts on best practices?

**Comment by ramonawalls** [comment]
I'm not sure I understand the question about how often to make parents, but perhaps you mean asserting parents with subclass of axioms rather than through equivalence axioms.

In your example above, the existing definition seems correct, except that it should be part of a lower jaw region (which I assume is just a typo).

You should not assert that one type of tooth is a part of another type of tooth (as when you suggested ('part of' some 'deciduous tooth or deciduous premolar tooth')). Subclass of is the relation to use here, not part of. 

If you were starting from scratch, you could define lower deciduous premolar 5 using an equivalency axiom as:

'premolar tooth 5' and 'deciduous tooth' and ('part of' some 'lower jaw region')

However, since 'deciduous premolar 5' already exists, when bother?

**Comment by ramonawalls** [comment]
If your question is about asserting subclass of parents versus inferring them from the equivalency axioms, the latter is generally preferred, because it will automatically build the hierarchy. Presumably the reason you see both parents asserted in UBERON for 'lower deciduous premolar' is because the release version has already been reasoned over and those relations are asserted by the reasoner.

**Comment by ramonawalls** [comment]
That particular term has been built, so I guess you are asking for general advise about whether or not to build those intermediary classes. I don't know that there is an accepted best practice. I tend to include them, because it makes the hierarchy a little more intuitive, but I suppose there is a reasonable argument to be made that you are cluttering up the hierarchy sometimes. One thing for sure is that if you need to use the grouping intermediate term (e.g., you want to search for all deciduous premolar 5 teeth, whether they are upper or lower), then you should include the class.
